name: WitPvP
main : witpvp.Wp
version: 0.1
commands:
   test:
      description: temporary test command
      usage: /<command>
   match:
      description: Create, edit or delete a match.
      usage: /<command> create,end,status,list,add
   hook:
      description: Hook onto a match so that other commands can be applied to that match.
      usage: /<command> [MATCHID]
   release:
      description: Removes the current hook, so that commands are no longer match-specific.
      usage: /<command>
   round:
      description: Create, edit or delete a round.
      usage: /<command> create,end,start,status,teleport,exit,delete
   world:
      description: Teleport, load or unload world files.
      usage: /<command> teleport,load,unload
   charge:
      description: Set your Charge Level to a desired value.
      usage: /<command> [INT]